branch-defaults:
  main:
    environment: Simple-django-based-CRM-dev
    group_suffix: null
global:
  application_name: Simple-django-based-CRM
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
