# Generated by Django 3.1.5 on 2021-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='order',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order',
            field=models.ManyToManyField(related_name='services', to='CRM.ServicesModel'),
        ),
    ]
