# Generated by Django 3.1.5 on 2021-01-14 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0002_auto_20210113_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='CRM.clientsmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='executioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executioner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Arrived', 'Поступил(а)'), ('Work in progress', 'В процессе'), ("Job's done", 'Готов'), ('Not_paid', 'Не оплачен'), ('Paid', 'Оплачен')], max_length=100),
        ),
    ]
