# Generated by Django 3.1.5 on 2021-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20210114_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
