# Generated by Django 3.1.5 on 2021-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20210114_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Поступил(а', 'Поступил(а)'), ('Согласован', 'Согласовано'), ('Отказ', 'Отказ'), ('Ожидает запчаст', 'Ожидает запчасти'), ('В процесс', 'В процессе'), ('Готов', 'Готов'), ('Не оплачен', 'Не оплачен'), ('Оплачен', 'Оплачен')], max_length=100),
        ),
    ]
