# Generated by Django 3.1.7 on 2021-04-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20210118_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
    ]
