# Generated by Django 3.1.7 on 2021-04-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_remove_ordermodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='CRM.clientsmodel'),
        ),
    ]
