# Generated by Django 3.1.7 on 2021-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20210410_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='CRM.ClientsModel'),
        ),
    ]
