# Generated by Django 3.1.7 on 2021-04-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_ordermodel_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='client',
            new_name='_client',
        ),
    ]
