# Generated by Django 3.1.7 on 2021-04-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_ordermodel__price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='clients',
        ),
    ]
