# Generated by Django 3.1.7 on 2021-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_remove_ordermodel_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='CRM.ClientsModel'),
        ),
    ]
